//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Approach_Crud_15022024.Models
{
    public class Country
    {
        public int cid { get; set; }
        public string cname { get; set; }
    }
}