//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Approach_Crud_15022024.Models
{
    public class personalinfo
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string Roll_No { get; set; }
        public int Salary { get; set; }

    }
}