//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Database_Approach_Crud_15022024.Models
{
    public class Student_data
    {
        public int Std_id { get; set; }
        public string Std_name { get; set; }
        public int Std_Age { get; set; }
        public string Email { get; set; }
        public int Department { get; set; }
        public int Position { get; set; }
    }


    //-------------for only Display purpose-----
    public class Student_data1
    {
        public int Std_id { get; set; }  
        public string Std_name { get; set; }
        public int Std_Age { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
    }

}